name = "Refined Interior"
description = "amazing amazon products that you may want to have."
keywords = "amazon, us, unitedstates, products."
image = "17431922_job204-wan-18.jpg"
theme = "light"
primary_color = "#e8deff"
text_align = "center"
gtag_id = "EMPTY"
base_url = "https://thevahidal.github.io/jake"

[[sections]]
title = "Featured ⭐"
description = "Porducts you can find"
direction = "column"
item_style = "outline"
[[sections.items]]

[[sections.items]]
title = "Bed Sheet Sets"
description = "The best Bed Sheet Set"
url = "https://amzn.to/42PyonT"
[[sections.items]]
title = "Murphy Bed"
description = "A peace of art for small apartments and homes"
url = "https://amzn.to/3RYJFMo"
[[sections.items]]
title = "Sponge Holder"
description = "A Product that will give your Kitchen a glow up"
url = "https://amzn.to/3Eszo8e"


[[sections]]
title = "Links"
description = "We are available on the following websites"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram"
url = "https://www.instagram.com/re.fined_interior"

